apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prequal-router.fullname" . }}
  labels:
    {{- include "prequal-router.labels" . | nindent 4 }}
---
# Read-only access to EndpointSlices, only in the namespace of the target Service.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "prequal-router.fullname" . }}
  namespace: {{ include "prequal-router.targetNamespace" . }}
  labels:
    {{- include "prequal-router.labels" . | nindent 4 }}
rules:
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "prequal-router.fullname" . }}
  namespace: {{ include "prequal-router.targetNamespace" . }}
  labels:
    {{- include "prequal-router.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "prequal-router.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "prequal-router.fullname" . }}
    namespace: {{ .Release.Namespace }}
